# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UICollectionViewTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	pod 'Masonry'
  # Pods for UICollectionViewTest

  target 'UICollectionViewTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UICollectionViewTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
