# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'zhhz' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for zhhz
  pod 'AFNetworking'

end

target 'zhsz' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for zhsz
  pod 'AFNetworking'

end
